### ISSUE TITLE
Hi. Cut me some slack, fam)))000)))

### ISSUE THREAD

**Issue by Piliponful** [iamwhaler/Particles-Inkremental#2]
You asked to help with webpack and react and didn't even added me as a collaborator to this repo. I won't force push to master or dev empty commits. I promise) Give me some authority here!

It's not yet finished but I wanted to push changes to a feature branch to show that I'm working on it and I don't forgot about it.

**Comment by Piliponful** [comment]
thanks

**Comment by iamwhaler** [comment]
<3
Thank you for help

**Comment by Piliponful** [comment]
As I said not finished yet. But will be in a near future. With a documentation on how to run it in README.md

**Comment by Piliponful** [comment]
|And can you give me some reasonable estimation on how idiotic the line "Cut me some slack, fam" reads. It's just that I've learned my casual talking from pewdiepie videos, so... I really need your feedback on that! Tnx!

**Comment by Piliponful** [comment]
And yeah. One more thing. Could you tell me honestly who did that...? It's the shittiest looking piece of murkup I've ever seen in my life. And I've seen many...(for example class names which spelled belongs as "beelong").
Why there was closing tags that doesn't much anything. Why there wasn't clear formatting? Any semi-decent code editor will do that for you with a few clicks. Why id names was without fucking quotations)))))0000?
![image](https://user-images.githubusercontent.com/17684958/34879097-d1c9ce28-f7b4-11e7-8276-d08899b5c27b.png)
I CAN use git blame but I wanna HEAR IT!!!
JK. It was actually pretty fun time refactoring that. Reminds me of Good Ol' Days.

**Comment by Piliponful** [comment]
But you"ll owe me a bear if I ever start drinking that shot. How bout that?

**Comment by Piliponful** [comment]
Actually first of all I"ll finish it

**Comment by Piliponful** [comment]
Actually first of all I"ll finish it

**Comment by iamwhaler** [comment]
Oh boy. The code is mine, never used that div before so didn't realize
that, thanks.
Can't argue that markup is shit, I just learn, so you can advise me what to
correct. For example, I don't know what is clear formatting, can you
explain?

2018-01-12 16:43 GMT+02:00 piliponful <notifications@github.com>:
